sh edit_cow_info.sh      
sh user_check_credit.sh             
sh user_get_wechatid.sh           
sh user_release_task_transaction.sh
sh edit_student_info.sh  
sh user_check_errand.sh             
sh user_login.sh                  
sh user_submit.sh
sh get_cow_info.sh       
sh user_check_question.sh           
sh user_logup.sh                  
sh user_submit_student.sh
sh get_range_task.sh     
sh user_check_task_self_receive.sh  
sh user_receive_task.sh           
sh user_verify.sh
sh get_student_info.sh   
sh user_check_task_self_release.sh  
sh user_recharge.sh               
sh user_withdraw.sh
sh get_typed_task.sh     
sh user_check_task.sh               
sh user_release_task_errand.sh
sh mission_search.sh     
sh user_check_transaction.sh        
sh user_release_task_question.sh           
sh user_get_balance.sh              
sh user_release_task.sh
